### ISSUE TITLE
Combining let & var statements

### ISSUE THREAD

**Issue by njsfield** [FAC10/week5-jajascript#56]
Any reason why you're combining *let* and *var* declarations in tflLogic.js ?
```javascript
  let westbound = [];
  let eastbound = [];
  var arr = data.map((value)=>[value.platformName, value.towards, value.timeToStation]);
  var sorted = arr.sort((a, b) => {
    return a[2] - b[2];
  })
```
Let is block scoped and var is not, see [here](http://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable) for further info (in general, var is virtually never needed if you're working in an environment which allows ES6 syntax).

Aside from that, all of these variables (westbound, eastbound, arr, sorted) are not redefined anywhere in your code, so you can store them as constants to ensure that don't get overridden by mistake;

```javascript
  const westbound = [];
  const eastbound = [];
  const arr = data.map((value)=>[value.platformName, value.towards, value.timeToStation]);
  const sorted = arr.sort((a, b) => {
    return a[2] - b[2];
  })
```

See [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/const)

**Comment by alexis-l8** [comment]
Thanks for your detailed response. The plan is to have the site refresh via setInterval so that the train arrival times refresh every few seconds. Therefore I will change the VARs to LETs.
