### ISSUE TITLE
CSS rules on `*`

### ISSUE THREAD

**Issue by oliverjam** [FAC10/week5-jajascript#59]
Is there any reason you're setting `color`, `font-family` and `font-weight` to every single element (with the `*` selector)?

By default these things will cascade and be inherited by children, so I think usually people just set this once on `body`.

**Comment by oliverjam** [comment]
You're also setting `margin: 0` on everything, so you probably don't need to do the same again to all the headings etc on [line 27](https://github.com/FAC10/week5-jajascript/blob/master/public/styles.css#L27)

**Comment by joeylouise** [comment]
@oliverjam we've removed the unnecessary margin:0 for line 27 but changing the `*` selector to `body` breaks thing for some reason
