### ISSUE TITLE
Codecov.key

### ISSUE THREAD

**Issue by njsfield** [FAC10/week5-jajascript#60]
Your sensitive data (api keys, environment variables) should not be stored in your master repo. If you need to use this data in your projects, you can add the file name to your .gitignore file to assert that it only exists on your local machines

Asides from that, your Codecov key does not need to be stored in this repository

**Comment by oliverjam** [comment]
FYI you don't need a CodeCov key at all if you're using Travis

**Comment by antoniotrkdz** [comment]
Thanks for the comments!
Even if it is not needed, I will add it to .gitignore
