### ISSUE TITLE
use of module.exports

### ISSUE THREAD

**Issue by ZooeyMiller** [FAC10/week5-jajascript#62]
In tflAPI.js and tflLogic.js when you use module.exports you export an object with one key value pair, being the function created in that module.

You can instead just export a single function, so rather than doing `module.exports = { myFunction: myFunction };`<br>You can instead just use `module.exports = myFunction`<br>Saves some characters in the long run :smile_cat:

**Comment by joeylouise** [comment]
@ZooeyMiller thanks! Have changed this now
