### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by njsfield** [FAC10/week5-jajascript#65]
You have a function called *tflTest*, that is the only exported function inside of a file called *tflLogic.js*. This is a bit confusing, if you're only exporting a single function, then try to name the file similarly, and just export the function and not an object containing a single key and value of the function itself

**Comment by oliverjam** [comment]
Related to this: your function in `tflAPI.js` is called `testRequest`. Is this a test or the real one?

**Comment by joeylouise** [comment]
We've renamed functions and changed how we export functions (exporting single functions and not object containing the function)
